version: "3.8"

services:
  #  db:
  #    container_name: mtg_db
  #    image: mysql:8.0
  #    command: --default-authentication-plugin=mysql_native_password
  #    volumes:
  #      - ./MySql/dbdata:/var/lib/mysql
  #      - ./MySql/init/:/docker-entrypoint-initdb.d
  #      # - ./MySql/config/my.cnf:/etc/mysql/my.cnf
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "3307:3306"

  main:
    container_name: iris
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
