[tool.poetry]
name = "iris-example"
version = "0.1.0"
description = ""
authors = ["Andrew Knoesen <andrew@spatialedge.co.za>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
